"""add word_count to documents

Revision ID: 0bf18c3db8c9
Revises: 4594434f6427
Create Date: 2026-07-03 22:50:43.381419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf18c3db8c9'
down_revision: Union[str, Sequence[str], None] = '4594434f6427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ch09_documents', sa.Column('word_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ch09_documents', 'word_count')
    # ### end Alembic commands ###
