"""create workspaces and documents

Revision ID: 4594434f6427
Revises: 
Create Date: 2026-07-03 22:50:17.268416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4594434f6427'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ch09_workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ch09_workspaces')),
    sa.UniqueConstraint('slug', name=op.f('uq_ch09_workspaces_slug'))
    )
    op.create_table('ch09_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['ch09_workspaces.id'], name=op.f('fk_ch09_documents_workspace_id_ch09_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ch09_documents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ch09_documents')
    op.drop_table('ch09_workspaces')
    # ### end Alembic commands ###
